#define NUM_BUTTONWIDTH                 60
#define NUM_LABELWIDTH                  65
#define LANGUAGE_LTR

// ============================================================================
// Context menus
// ============================================================================

// Rainmeter menu
#define STR_UPDATEAVAILABLE             "تازہ کاری دستیاب ہے"
#define STR_LANGUAGEOBSOLETE            "زبان پرانی ہو گئی ہے"
#define STR_MANAGE                      "انتظام کریں"
#define STR_ABOUT                       "کے بارے میں"
#define STR_HELP                        "مدد"
#define STR_SKINS                       "کھالیں"
#define STR_NOSKINS                     "کوئی کھالیں دستیاب نہیں ہیں"
#define STR_OPENFOLDER                  "فولڈر کھولیں"
#define STR_DISABLEDRAGGING             "گھسیٹنا غیر فعال کریں"
#define STR_THEMES                      "ترتیب"
#define STR_NOTHEMES                    "کوئی ترتیب دستیاب نہیں ہے"
#define STR_EDITSETTINGS                "ترتیبات میں ترمیم کریں"
#define STR_REFRESHALL                  "سب کو تازہ کریں"
#define STR_LOGGING                     "لاگنگ"
#define STR_SHOWLOGFILE                 "لاگ فائل دکھائیں"
#define STR_STARTLOGGING                "لاگنگ شروع کریں"
#define STR_STOPLOGGING                 "لاگنگ بند کریں"
#define STR_DELETELOGFILE               "لاگ فائل حذف کریں"
#define STR_DEBUGMODE                   "ڈیبگ موڈ"
#define STR_EXIT                        "باہر نکلیں"
#define STR_FAVORITES                   "پسندیدہ"
#define STR_NOFAVORITES                 "کوئی پسندیدہ تعریف نہیں کی گئی"

// Skin menu
#define STR_VARIANTS                    "متغیرات"
#define STR_SETTINGS                    "ترتیبات"
#define STR_POSITION                    "پوزیشن"
#define STR_DISPLAYMONITOR              "ڈسپلے مانیٹر"
#define STR_USEDEFAULTMONITOR           "ڈیفالٹ استعمال کریں: پرائمری مانیٹر"
#define STR_VIRTUALSCREEN               "@0: ورچوئل اسکرین"
#define STR_AUTOSELECTMONITOR           "ونڈو کی پوزیشن کی بنیاد پر خودکار انتخاب"
#define STR_STAYTOPMOST                 "سب سے اوپر رہیں"
#define STR_TOPMOST                     "سب سے اوپر"
#define STR_NORMAL                      "معمول"
#define STR_BOTTOM                      "نیچے"
#define STR_ONDESKTOP                   "ڈیسک ٹاپ پر"
#define STR_FROMRIGHT                   "دائیں سے"
#define STR_FROMBOTTOM                  "نیچے سے"
#define STR_XASPERCENTAGE               "X فیصد کے طور پر"
#define STR_YASPERCENTAGE               "Y فیصد کے طور پر"
#define STR_TRANSPARENCY                "شفافیت"
#define STR_ONHOVER                     "ہوور پر"
#define STR_FADEIN                      "مدھم ہونا"
#define STR_FADEOUT                     "مدھم ہونا بند کریں"
#define STR_HIDEONMOUSEOVER             "ماؤس اوور پر چھپائیں"
#define STR_DRAGGABLE                   "گھسیٹا جا سکتا ہے"
#define STR_SAVEPOSITION                "پوزیشن محفوظ کریں"
#define STR_SNAPTOEDGES                 "کناروں سے جڑیں"
#define STR_CLICKTHROUGH                "کلک تھرو"
#define STR_KEEPONSCREEN                "اسکرین پر رکھیں"
#define STR_MANAGESKIN                  "کھال کا انتظام کریں"
#define STR_EDITSKIN                    "کھال میں ترمیم کریں"
#define STR_REFRESHSKIN                 "کھال کو تازہ کریں"
#define STR_UNLOADSKIN                  "کھال ان لوڈ کریں"
#define STR_CUSTOMSKINACTIONS           "حسب ضرورت کھال کے اعمال"
#define STR_FAVORITE                    "پسندیدہ"
// ============================================================================
// Dialogs
// ============================================================================

#define STR_CLOSE                       "بند کریں"

// About dialog
#define STR_ABOUTRAINMETER              "رین میٹر کے بارے میں"
#define STR_LOG                         "لاگ"
#define STR_MEASURE                     "ماپ"
#define STR_MEASURES                    "ماپیں"
#define STR_VARIABLES                   "متغیرات"
#define STR_PLUGINS                     "پلگ ان"
#define STR_VERSION                     "ورژن"
#define STR_TYPE                        "قسم"
#define STR_TIME                        "وقت"
#define STR_SOURCE                      "ماخذ"
#define STR_MESSAGE                     "پیغام"
#define STR_NAME                        "نام"
#define STR_RANGE                       "حد"
#define STR_VALUE                       "قدر"
#define STR_AUTHOR                      "مصنف"
#define STR_ERROR                       "خرابی"
#define STR_WARNING                     "انتباہ"
#define STR_NOTICE                      "نوٹس"
#define STR_DEBUG                       "ڈیبگ"
#define STR_CLEAR                       "صاف کریں"
#define STR_GETLATESTVERSION            "تازہ ترین ورژن حاصل کریں <a href=""http://rainmeter.net"">rainmeter.net</a> سے۔"
#define STR_COPYRIGHTNOTICE             "کے تحت تقسیم کیا گیا <a href=""http://www.gnu.org/licenses"">GNU GPL v2</a> لائسنس۔"
#define STR_COPYTOCLIPBOARD             "کلپ بورڈ پر کاپی کریں"
#define STR_NUMBER                      "نمبر"
#define STR_STRING                      "اسٹرنگ"
#define STR_EXTERNALPLUGINS             "بیرونی پلگ ان"
#define STR_BUILTINPLUGINS              "بلٹ ان پلگ ان"
// Manage dialog
#define STR_MANAGERAINMETER             "رین میٹر کا انتظام کریں"
#define STR_ACTIVESKINS                 "فعال کھالیں"
#define STR_EXPAND                      "پھیلائیں"
#define STR_COLLAPSE                    "سمیٹیں"
#define STR_CREATERMSKIN                ".rmskin پیکج بنائیں..."
#define STR_OPENLOG                     "لاگ کھولیں"
#define STR_LOAD                        "لوڈ کریں"
#define STR_UNLOAD                      "ان لوڈ کریں"
#define STR_REFRESH                     "تازہ کریں"
#define STR_EDIT                        "ترمیم کریں"
#define STR_AUTHORSC                    "مصنف:"
#define STR_VERSIONSC                   "ورژن:"
#define STR_LICENSESC                   "لائسنس:"
#define STR_INFORMATIONSC               "معلومات:"
#define STR_ADDMETADATA                 "<a>میٹا ڈیٹا شامل کریں</a>"
#define STR_COORDINATESSC               "مختصات:"
#define STR_POSITIONSC                  "مقام:"
#define STR_LOADORDERSC                 "لوڈ آرڈر:"
#define STR_TRANSPARENCYSC              "شفافیت:"
#define STR_ONHOVERSC                   "ہوور پر:"
#define STR_DONOTHING                   "کچھ نہ کریں"
#define STR_HIDE                        "چھپائیں"
#define STR_SAVENEWTHEME                "نئی ترتیب محفوظ کریں"
#define STR_THEMEDESCRIPTION            "ایک ترتیب آپ کو اپنے رین میٹر سیٹ اپ کی موجودہ حالت کو محفوظ اور بحال کرنے کی اجازت دیتی ہے، جس میں لوڈ اور ان لوڈ کھالوں کے مقامات شامل ہیں۔ کھال کے فولڈرز اور فائلیں محفوظ نہیں ہوتیں۔"
#define STR_SAVEASEMPTYTHEME            "خالی ترتیب کے طور پر محفوظ کریں"
#define STR_EXCLUDEUNUSEDSKINS          "غیر استعمال شدہ کھالوں کو شامل نہ کریں"
#define STR_INCLUDEWALLPAPER            "موجودہ وال پیپر شامل کریں"
#define STR_NAMESC                      "نام:"
#define STR_SAVE                        "محفوظ کریں"
#define STR_SAVEDTHEMES                 "محفوظ کردہ ترتیبیں"
#define STR_DELETE                      "حذف کریں"
#define STR_BACKUP                      "بیک اپ"
#define STR_BACKUPDESCRIPTION           "بیک اپ آپ کو اپنے سیٹ اپ کی مکمل کاپی محفوظ کرنے کی اجازت دیتا ہے، جس میں کھالیں اور اعداد و شمار شامل ہیں۔ ایک ترتیب کے برعکس، بیک اپ کو بحال کرنے سے محفوظ ہونے کے بعد سے آپ کی کھالوں میں کی گئی تمام ترامیم اور اپ ڈیٹس کو تبدیل کر دیا جائے گا۔"
#define STR_BACKUPE                     "بیک اپ..."
#define STR_LANGUAGESC                  "زبان:"
#define STR_EDITORSC                    "ایڈیٹر:"
#define STR_GENERAL                     "عام"
#define STR_CHECKFORUPDATES             "تازہ کاریوں کے لیے چیک کریں"
#define STR_SHOWNOTIFAREAICON           "اطلاع کے علاقے کا آئیکن دکھائیں"
#define STR_RESETSTATISTICS             "اعداد و شمار ری سیٹ کریں"
#define STR_LOGTOFILE                   "فائل میں لاگ کریں"
#define STR_HARDWAREACCELERATED         "ہارڈ ویئر ایکسیلیریشن استعمال کریں"
#define STR_AUTOMATICUPDATE             "تازہ کاریاں خود بخود انسٹال کریں"
#define STR_GAMEMODE                    "گیم موڈ"
#define STR_GAMEMODE_START              "گیم موڈ شروع کریں"
#define STR_GAMEMODE_STOP               "گیم موڈ بند کریں"
#define STR_GAMEMODE_FULLSCREEN         "فل اسکرین گیمز"
#define STR_GAMEMODE_PROCESSLIST        "اضافی عمل کی فہرست"
#define STR_GAMEMODE_PROCESSLISTSC      "اضافی عمل کی فہرست:"
#define STR_GAMEMODE_SETTINGS_DESC      "آپ ٹرے آئیکن کے سیاق و سباق کے مینو کا استعمال کرتے ہوئے دستی طور پر گیم موڈ شروع یا بند کر سکتے ہیں۔ گیم موڈ کو دستی طور پر شروع/بند کرنے سے ""فل اسکرین گیمز"" اور ""اضافی عمل کی فہرست"" کے دونوں چیک باکسز غیر فعال ہو جائیں گے۔ ان اشیاء کو دوبارہ فعال کرنا ضروری ہوگا تاکہ رین میٹر انہیں دوبارہ مانیٹر کرنا شروع کر سکے۔\n\nمزید معلومات کے لیے ""مدد"" بٹن پر کلک کریں۔"
#define STR_GAMEMODE_ACTIONS_ONSTART    "شروع کرتے وقت"
#define STR_GAMEMODE_ACTIONS_ONSTOP     "روکنے پر"
#define STR_GAMEMODE_ACTIONS_DESC       "گیم موڈ شروع/بند کرتے وقت انجام دینے والے عمل کو منتخب کریں۔ ""شروع کرتے وقت"" تمام کھالوں کو ان لوڈ کر سکتا ہے یا ترتیب لوڈ کر سکتا ہے۔ ""روکنے پر"" موجودہ ترتیب یا دوسری ترتیب کو دوبارہ لوڈ کر سکتا ہے۔"
#define STR_GAMEMODE_ACTIONS_UNLOADALL  "تمام کھالیں ان لوڈ کریں"
#define STR_GAMEMODE_ACTIONS_CURRENT    "موجودہ ترتیب لوڈ کریں"

// NewSkin dialog
#define STR_CREATENEWSKIN               "نئی کھال بنائیں"
#define STR_NEWSKIN                     "نئی کھال"
#define STR_TEMPLATE                    "سانچہ"
#define STR_TEMPLATEE                   "سانچہ..."
#define STR_ADDFOLDER                   "فولڈر شامل کریں"
#define STR_ADDSKIN                     "کھال شامل کریں"
#define STR_RENAME                      "نام تبدیل کریں"
#define STR_SAVENEWTEMPLATE             "نیا سانچہ محفوظ کریں"
#define STR_SAVEDTEMPLATES              "محفوظ کردہ سانچے"
#define STR_USEDEFAULTTEMPLATE          "ڈیفالٹ سانچہ استعمال کریں"
// ============================================================================
// Safe start
// ============================================================================

#define STR_SAFESTART_TITLE             "رین میٹر محفوظ آغاز"
#define STR_SAFESTART_MESSAGE           "یہ تمام کھالوں کو ان لوڈ کرے گا اور رین میٹر کو ڈیفالٹ ""illustro"" کھالوں کے ساتھ شروع کرے گا۔\n\nآپ کی موجودہ ترتیب اس کے طور پر محفوظ کی جائے گی: @Backup\n\nاسے اس وقت استعمال کریں جب آپ کو رین میٹر شروع کرنے میں دشواری ہو۔\n\nکیا آپ رین میٹر محفوظ آغاز میں داخل ہونا چاہتے ہیں؟"

// ============================================================================
// Messages
// ============================================================================

#define STR_RESTART_CONFIRM             "اس تبدیلی کے لیے رین میٹر کو دوبارہ شروع کرنا ضروری ہے۔\n\nکیا آپ ابھی رین میٹر کو دوبارہ شروع کرنا چاہتے ہیں؟"
#define STR_SETTINGSNOTWRITABLE         "Rainmeter.ini قابل تحریر نہیں ہے۔ سیٹنگز محفوظ نہیں کی جائیں گی۔"
#define STR_SETTINGSMOVEFILE            "رین میٹر بند کریں اور سیٹنگز فائل کو یہاں سے منتقل کریں:\n%1\n\nیہاں:\n%2\n\nمتبادل کے طور پر، فائل کو ہٹا دیں (سیٹنگز ختم ہو جائیں گی) اور یہ اگلی بار لانچ ہونے پر خود بخود دوبارہ بن جائے گی۔"
#define STR_SETTINGSREADONLY            "یقینی بنائیں کہ فائل کو ریڈ اونلی کے طور پر سیٹ نہیں کیا گیا اور فولڈر قابل تحریر ہے۔ فائل یہاں واقع ہے:\n%1"
#define STR_THEMEALREADYEXISTS          "ترتیب ""%1"" پہلے سے موجود ہے۔\n\nکیا آپ اسے تبدیل کرنا چاہتے ہیں؟"
#define STR_THEMESAVEFAIL               "ترتیب محفوظ کرنے میں ناکام:\n%1"
#define STR_THEMEDELETE                 "کیا آپ واقعی ترتیب ""%1"" کو حذف کرنا چاہتے ہیں؟"
#define STR_LOGFILECREATEFAIL           "لاگ فائل بنانے میں ناکام:\n%1"
#define STR_LOGFILEDELETE               "کیا آپ واقعی لاگ فائل کو حذف کرنا چاہتے ہیں؟\n%1"
#define STR_NOAVAILABLESKINS            "یہاں کوئی دستیاب کھالیں نہیں ہیں:\n%1"
#define STR_UNABLETOACTIVATESKIN        "کھال کو فعال کرنے میں ناکام ""%1\\%2"": فائل نہیں ملی۔"
#define STR_UNABLETOREFRESHSKIN         "کھال کو ریفریش کرنے میں ناکام ""%1\\%2"": فائل نہیں ملی۔"
#define STR_NEWVERSIONREQUIRED          "کھال ""%1\\%2"" کے لیے رین میٹر %3 یا اس سے زیادہ کی ضرورت ہے۔ تازہ ترین ورژن rainmeter.net سے ڈاؤن لوڈ کریں۔"
#define STR_NOMETERSINSKIN              "کھال ""%1\\%2"" میں کوئی میٹرز شامل نہیں ہیں اور اسے غیر فعال کر دیا جائے گا۔\n\nیہ فائل خراب ہو سکتی ہے یا یہ ایک درست کھال نہیں ہو سکتی۔"
#define STR_INCLUDEINFINITELOOP         "آپ نے @include کے ساتھ ایک لامحدود لوپ بنایا ہے۔ براہ کرم اپنی کھال کو چیک کریں۔"
#define STR_CREATEFOLDERFAIL            "فولڈر بنانے میں ناکام: %1"
#define STR_CREATEFILEFAIL              "فائل بنانے میں ناکام: %1"
#define STR_FOLDEREXISTS                "فولڈر ""%1"" پہلے سے موجود ہے۔"
#define STR_FILEEXISTS                  "فائل ""%1"" پہلے سے موجود ہے۔"
#define STR_RENAMEFOLDERFAIL            "فولڈر ""%1"" کا نام تبدیل نہیں کیا جا سکا۔\nخرابی کوڈ: %2"
#define STR_RENAMEFILEFAIL              "فائل ""%1"" کا نام تبدیل نہیں کیا جا سکا۔\nخرابی کوڈ: %2"
#define STR_FOLDERDELETE                "کیا آپ واقعی اس فولڈر کو حذف کرنا چاہتے ہیں؟\n%1"
#define STR_FILEDELETE                  "کیا آپ واقعی اس فائل کو حذف کرنا چاہتے ہیں؟\n%1"
#define STR_FOLDERDELETEFAIL            "فولڈر کو حذف کرنے میں ناکام:\n%1"
#define STR_FILEDELETEFAIL              "فائل کو حذف کرنے میں ناکام:\n%1"
#define STR_TEMPLATEDOESNOTEXIST        "سانچہ ""%1"" موجود نہیں ہے۔\nکیا آپ ڈیفالٹ سانچہ استعمال کرنا چاہتے ہیں؟"
#define STR_TEMPLATEEXISTS              "سانچہ ""%1"" پہلے سے موجود ہے۔"
#define STR_TEMPLATEFOLDERFAIL          "سانچہ فولڈر بنانے میں ناکام۔"
#define STR_TEMPLATEFILEFAIL            "سانچہ فائل بنانے میں ناکام: %1"
#define STR_TEMPLATEDELETE              "کیا آپ واقعی سانچہ ""%1"" کو حذف کرنا چاہتے ہیں؟"

// ============================================================================
// Notifications
// ============================================================================

#define STR_WELCOME                     "رین میٹر میں خوش آمدید"
#define STR_CLICKTOMANAGE               "کھالوں اور سیٹنگز کو مینیج کرنے کے لیے رین میٹر آئیکن پر کلک کریں۔"
#define STR_CLICKTODOWNLOAD             "رین میٹر %1 ڈاؤن لوڈ کرنے کے لیے یہاں کلک کریں۔"
#define STR_INSTALL_NEW_VERSION         "نیا ورژن انسٹال کریں"
#define STR_CLICK_TO_INSTALL            "ورژن %1 انسٹال کرنے کے لیے رین میٹر کو دوبارہ شروع کریں۔"
